name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: sbt scalafmtCheckAll

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: sbt jacoco
      - uses: codecov/codecov-action@v3
        with:
          flags: unit-tests

  integration-test:
    runs-on: ubuntu-latest
    # disable for PRs from forks
    if: ${{ !github.event.pull_request.head.repo.fork }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"
      - run: sbt IntegrationTest/jacoco
      - uses: codecov/codecov-action@v3
        with:
          flags: integration-tests

  all-checks:
    needs: [lint, unit-test, integration-test]
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
